import mongoose, { Document, Schema } from 'mongoose';

// Source of the availability data
export type AvailabilitySource =
	| 'admin' // Added by admin
	| 'user_contribution' // Reported by user
	| 'seed_data' // Initial seed data
	| 'api_fetch' // Fetched from external API
	| 'store_api'; // From store's own API

// Moderation status for user contributions
export type ModerationStatus = 'confirmed' | 'pending' | 'rejected';

export interface IAvailability extends Document {
	_id: mongoose.Types.ObjectId;
	productId: mongoose.Types.ObjectId;
	storeId: mongoose.Types.ObjectId;

	// Source tracking
	source: AvailabilitySource;
	reportedBy?: mongoose.Types.ObjectId; // User who reported (if user_contribution)

	// Moderation
	moderationStatus: ModerationStatus;
	moderatedBy?: mongoose.Types.ObjectId; // Admin who moderated
	moderatedAt?: Date;
	// Review tracking (separate from moderation status for trusted contributors)
	needsReview: boolean; // True if content needs admin review
	trustedContribution: boolean; // True if submitted by a trusted contributor
	reviewedBy?: mongoose.Types.ObjectId; // Admin who reviewed
	reviewedAt?: Date;

	// Details
	priceRange?: string;
	notes?: string; // Optional notes from reporter
	lastConfirmedAt?: Date;
	lastFetchedAt?: Date; // When we last fetched from API
	isStale?: boolean; // Flag if data is older than threshold

	createdAt?: Date; // Auto-generated by timestamps: true
	updatedAt?: Date; // Auto-generated by timestamps: true
}

const availabilitySchema = new Schema<IAvailability>(
	{
		productId: {
			type: Schema.Types.ObjectId,
			ref: 'Product',
			required: true,
			index: true,
		},
		storeId: {
			type: Schema.Types.ObjectId,
			ref: 'Store',
			required: true,
			index: true,
		},
		// Source tracking
		source: {
			type: String,
			enum: [
				'admin',
				'user_contribution',
				'seed_data',
				'api_fetch',
				'store_api',
			],
			default: 'admin',
		},
		reportedBy: {
			type: Schema.Types.ObjectId,
			ref: 'User',
			index: true,
		},
		// Moderation
		moderationStatus: {
			type: String,
			enum: ['confirmed', 'pending', 'rejected'],
			default: 'pending', // Require moderation for user contributions
			index: true,
		},
		moderatedBy: {
			type: Schema.Types.ObjectId,
			ref: 'User',
		},
		moderatedAt: {
			type: Date,
		},
		// Review tracking (separate from moderation status for trusted contributors)
		needsReview: {
			type: Boolean,
			default: true, // All user content needs review
			index: true,
		},
		trustedContribution: {
			type: Boolean,
			default: false, // True if submitted by a trusted contributor
			index: true,
		},
		reviewedBy: {
			type: Schema.Types.ObjectId,
			ref: 'User',
		},
		reviewedAt: {
			type: Date,
		},
		// Details
		priceRange: {
			type: String,
			trim: true,
		},
		notes: {
			type: String,
			trim: true,
			maxlength: 500,
		},
		lastConfirmedAt: {
			type: Date,
		},
		lastFetchedAt: {
			type: Date,
		},
		isStale: {
			type: Boolean,
			default: false,
		},
	},
	{
		timestamps: true,
	}
);

// Compound index for efficient lookups
availabilitySchema.index({ productId: 1, storeId: 1 }, { unique: true });
// Index for finding pending reports
availabilitySchema.index({ moderationStatus: 1, createdAt: -1 });

export const Availability = mongoose.model<IAvailability>(
	'Availability',
	availabilitySchema
);
